import { useEffect, useState } from "react"

type Page = "dashboard" | "population" | "exceptions" | "paper"
type Rule = { rule_id: string; rule_name: string; result: string; detail: string }
type Case = { change_id: string; case_id?: string; vendor_id?: string; vendor_name?: string; request_id?: string; requested_at?: string; requested_by?: string; status?: "normal" | "review" | "error"; reason?: string; approval_ids?: string[]; evidence_ids?: string[]; rules?: Rule[] }
type Day1Payload = { summary: Record<string, number>; population: Case[]; exceptions?: Case[]; input_errors?: Case[]; persistence?: { database: string; valid_population_rows: number } }
type PaperSample = { sample_id: string; change_id: string; case_id: string; vendor_id: string; vendor_name: string; selection_reason: string; day1_status: "normal" | "review"; source_ids: { approval_ids: string[]; evidence_ids: string[]; payment_ids: string[] }; agent_draft: { procedure: string; facts: string[]; draft_assessment: string; additional_follow_up: string[]; citations: string[] }; requires_human_review: true }
type WorkingPaper = { schema_version: string; generated_at: string; summary: { sample_count: number; normal_sample_count: number; review_sample_count: number; draft_count: number }; samples: PaperSample[] }
type PaperResponse = { status: "ready" | "not_generated" | "invalid"; message: string; working_paper: WorkingPaper | null; validation: { valid: boolean; errors: string[] } }

const labels: Record<string, string> = { population_count: "모집단", valid_count: "유효", normal_count: "정상", review_count: "검토 필요", input_error_count: "입력 오류" }
const statusText = { normal: "정상", review: "검토 필요", error: "입력 오류" }
const resultText = { pass: "통과", fail: "위반", not_applicable: "제외" }

async function requestDay1() {
  const response = await fetch("/api/control-test/run", { method: "POST" })
  if (!response.ok) throw new Error(`통제 테스트 API 오류 (${response.status})`)
  return response.json() as Promise<Day1Payload>
}
async function requestPaper() {
  const response = await fetch("/api/day2/working-paper")
  if (!response.ok) throw new Error(`검토자료 API 오류 (${response.status})`)
  return response.json() as Promise<PaperResponse>
}
function StatusBadge({ status }: { status: Case["status"] }) { return status ? <span className={`status-badge ${status}`}>{statusText[status]}</span> : null }
function PageHeader({ eyebrow = "Day 2 · 검토자료", title, description, action }: { eyebrow?: string; title: string; description: string; action?: React.ReactNode }) { return <header className="page-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="page-description">{description}</p></div>{action}</header> }
function Workflow() { return <section className="card"><div className="section-heading"><div><p className="eyebrow">업무 진행</p><h2>통제 테스트 흐름</h2></div><span className="quiet-badge">Day 2 · 검토자료</span></div><ol className="workflow">{["모집단 확인", "규칙 테스트", "결과 저장", "증적 조사", "검토자료 초안"].map((label, index) => <li className="done" key={label}><span>✓</span><div><strong>{label}</strong><small>{index === 4 ? "이번 단계" : "확인 완료"}</small></div></li>)}</ol></section> }
function Shell({ page, setPage, children, ready }: { page: Page; setPage: (page: Page) => void; children: React.ReactNode; ready: boolean }) {
  const nav: { id: Page; label: string; step: string; enabled: boolean }[] = [
    { id: "dashboard", label: "대시보드", step: "01", enabled: true },
    { id: "population", label: "모집단 확인", step: "02", enabled: true },
    { id: "exceptions", label: "예외 검토", step: "03", enabled: true },
    { id: "paper", label: "검토자료", step: "04", enabled: true },
  ]
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">AX</span><div><strong>내부통제 AX</strong><small>실습용 업무 화면</small></div></div><div className="control-context"><span>현재 통제</span><strong>거래처 계좌 변경</strong><small>CTL-VC-001</small></div><nav aria-label="통제 테스트 단계">{nav.map((item) => <button key={item.id} className={page === item.id ? "active" : ""} disabled={!item.enabled} onClick={() => setPage(item.id)} aria-current={page === item.id ? "page" : undefined}><span>{item.step}</span>{item.label}</button>)}<button className="prepared" disabled title="Day 3에서 연결됩니다."><span>05</span>최종 검토 <small>(준비)</small></button></nav><div className="sidebar-note"><strong>Day 2 화면 연결 완료</strong><p>Agent 초안은 최종 결론이 아니며 담당자 검토가 필요합니다.</p></div></aside><div className="workspace"><header className="topbar"><div><strong>거래처 계좌 변경 통제</strong><span>{page === "dashboard" ? "대시보드" : page === "population" ? "모집단 확인" : page === "exceptions" ? "예외 검토" : "검토자료"}</span></div><span className={`connection ${ready ? "" : "caution"}`}>{ready ? "API 연결 O" : "API 연결 중"}</span></header><main className="main-content">{children}</main></div></div>
}
function Dashboard({ data, paper, setPage, onReload }: { data: Day1Payload; paper: WorkingPaper; setPage: (page: Page) => void; onReload: () => void }) {
  const summary = paper.summary
  return <><PageHeader eyebrow="Day 2 · 검토자료" title="거래처 계좌 변경 통제" description="Day 1 결과를 고정 샘플과 증적으로 이어 검토자료 초안으로 확인합니다." action={<button className="primary-button" onClick={onReload}>Day 1 다시 실행</button>} /><section className="metric-grid" aria-label="Day 1 요약">{["population_count", "valid_count", "normal_count", "review_count", "input_error_count"].map((key) => <article className="metric-card" key={key}><span>{labels[key]}</span><strong>{data.summary[key] ?? 0}</strong><small>Day 1 결과</small></article>)}</section><section className="card day2-overview prepared-card"><div className="section-heading"><div><p className="eyebrow">Working paper</p><h2>검토자료 초안이 준비되었습니다</h2></div><button className="secondary-button" onClick={() => setPage("paper")}>검토자료 열기</button></div><div className="day2-summary"><div><span>검토 샘플</span><strong>{summary.sample_count}건</strong></div><div><span>정상 샘플</span><strong>{summary.normal_sample_count}건</strong></div><div><span>검토 필요</span><strong>{summary.review_sample_count}건</strong></div><div><span>Agent 초안</span><strong>{summary.draft_count}건</strong></div></div><p>초안은 근거와 추가 확인 항목을 정리한 작업자료입니다. 사람의 최종 검토 결과를 대신하지 않습니다.</p></section><Workflow /></>
}
function PopulationPage({ data }: { data: Day1Payload }) { return <><PageHeader eyebrow="Day 1 · 모집단" title="모집단 확인" description="Day 1에서 읽고 저장한 변경 요청을 다시 확인합니다." /><section className="card"><div className="section-heading"><div><p className="eyebrow">vendor_changes.csv</p><h2>변경 요청 {data.population.length}건</h2></div></div><div className="table-wrap"><table><thead><tr><th>변경 ID</th><th>Case ID</th><th>거래처 ID</th><th>요청 ID</th><th>상태</th></tr></thead><tbody>{data.population.map((item) => <tr key={item.change_id}><td className="id-cell">{item.change_id}</td><td>{item.case_id ?? "-"}</td><td>{item.vendor_id ?? "-"}</td><td>{item.request_id ?? "-"}</td><td><StatusBadge status={item.status} /></td></tr>)}</tbody></table></div></section></> }
function ExceptionsPage({ data }: { data: Day1Payload }) { const detail = data.exceptions?.[0]; return <><PageHeader eyebrow="Day 1 · 예외" title="예외 검토" description="통제 결과와 규칙별 사유를 확인합니다." /><div className="exception-layout"><section className="card exception-list"><div className="section-heading"><div><p className="eyebrow">R-01 ~ R-04</p><h2>예외 {(data.exceptions ?? []).length}건</h2></div></div>{(data.exceptions ?? []).map((item) => <div className="exception-item" key={item.change_id}><div><span className="id-cell">{item.change_id}</span><strong>{item.vendor_name}</strong><p>{item.reason}</p></div><StatusBadge status={item.status} /></div>)}</section><section className="card exception-detail">{detail ? <><div className="detail-title"><div><p className="eyebrow">대표 예외</p><h2>{detail.change_id}</h2><span>{detail.vendor_name}</span></div><StatusBadge status={detail.status} /></div><p>{detail.reason}</p><div className="rule-list">{(detail.rules ?? []).map((rule) => <div className={`rule-row ${rule.result === "fail" ? "fail" : ""}`} key={rule.rule_id}><strong>{rule.rule_id} · {rule.rule_name}</strong><span>{resultText[rule.result as keyof typeof resultText] ?? rule.result}</span><small>{rule.detail}</small></div>)}</div></> : <p>예외가 없습니다.</p>}</section></div></> }
function InputErrors({ errors }: { errors: Case[] }) { return <section className="card"><div className="section-heading"><div><p className="eyebrow">입력 품질</p><h2>입력 오류 행 {errors.length}건</h2></div><span className="status-badge error">통제 판정 제외</span></div><div className="table-wrap"><table><thead><tr><th>변경 ID</th><th>거래처 ID</th><th>오류 사유</th><th>상태</th></tr></thead><tbody>{errors.map((item) => <tr key={item.change_id}><td className="id-cell">{item.change_id}</td><td>{item.vendor_id ?? "-"}</td><td>{item.reason ?? "입력값을 확인해주세요."}</td><td><StatusBadge status={item.status} /></td></tr>)}</tbody></table></div></section> }
function PaperPage({ paper, selected, setSelected }: { paper: WorkingPaper; selected: string; setSelected: (id: string) => void }) { const sample = paper.samples.find((item) => item.change_id === selected) ?? paper.samples[0]; return <><PageHeader title="검토자료" description="고정 샘플별 증적과 Agent 초안을 읽고 추가 확인 항목을 메모합니다." /><div className="day2-summary"><div className="card"><span>샘플</span><strong>{paper.summary.sample_count}건</strong></div><div className="card"><span>정상</span><strong>{paper.summary.normal_sample_count}건</strong></div><div className="card"><span>검토 필요</span><strong>{paper.summary.review_sample_count}건</strong></div><div className="card"><span>생성 시각</span><strong>{paper.generated_at}</strong></div></div><div className="paper-layout"><section className="card paper-sample-list"><div className="section-heading"><div><p className="eyebrow">Day 2 samples</p><h2>검토 샘플</h2></div><span className="quiet-badge">담당자 검토 필요</span></div>{paper.samples.map((item) => <button className={`paper-sample ${sample?.change_id === item.change_id ? "selected" : ""}`} key={item.change_id} onClick={() => setSelected(item.change_id)}><div><span className="id-cell">{item.change_id}</span><strong>{item.vendor_name}</strong><small>{item.selection_reason}</small></div><span className="status-badge review">초안</span></button>)}</section><section className="card paper-detail">{sample ? <><div className="detail-title"><div><p className="eyebrow">{sample.sample_id}</p><h2>{sample.vendor_name}</h2><span className="id-cell">{sample.change_id}</span></div><span className="quiet-badge">최종 결론 아님</span></div><dl className="persistence-card"><div><dt>Case ID</dt><dd>{sample.case_id}</dd></div><div><dt>Day 1 상태</dt><dd>{sample.day1_status}</dd></div><div><dt>승인 참조</dt><dd>{sample.source_ids.approval_ids.join(", ") || "없음"}</dd></div><div><dt>증적 참조</dt><dd>{sample.source_ids.evidence_ids.join(", ") || "없음"}</dd></div></dl><div className="draft-card"><strong>Agent 초안</strong><p>{sample.agent_draft.draft_assessment}</p><h3>수행 절차</h3><p>{sample.agent_draft.procedure}</p><h3>추가 확인 항목</h3>{sample.agent_draft.additional_follow_up.length ? <ul>{sample.agent_draft.additional_follow_up.map((item) => <li key={item}>{item}</li>)}</ul> : <p>추가 확인 항목 없음</p>}</div></> : <p>샘플이 없습니다.</p>}</section></div></> }
export default function App() {
  const [page, setPage] = useState<Page>("dashboard")
  const [data, setData] = useState<Day1Payload | null>(null)
  const [paper, setPaper] = useState<WorkingPaper | null>(null)
  const [selected, setSelected] = useState("CHG-2608-023")
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState("")
  const load = () => { setLoading(true); setError(""); void Promise.all([requestDay1(), requestPaper()]).then(([day1, nextPaper]) => { setData(day1); setPaper(nextPaper.working_paper) }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "API 오류")).finally(() => setLoading(false)) }
  useEffect(load, [])
  const ready = !loading && !error && Boolean(data && paper)
  let content: React.ReactNode = null
  if (data && paper) {
    if (page === "population") content = <PopulationPage data={data} />
    else if (page === "exceptions") content = <><ExceptionsPage data={data} /><InputErrors errors={data.input_errors ?? []} /></>
    else if (page === "paper") content = <PaperPage paper={paper} selected={selected} setSelected={setSelected} />
    else content = <Dashboard data={data} paper={paper} setPage={setPage} onReload={load} />
  }
  return <Shell page={page} setPage={setPage} ready={ready}>{loading || error ? <div className={`state-card ${error ? "error-state" : ""}`} role={error ? "alert" : "status"}>{loading ? <><span className="spinner" /><strong>Day 1과 검토자료를 불러오는 중입니다.</strong></> : <><strong>API 연결 상태를 확인해주세요.</strong><span>{error}</span><button className="secondary-button" onClick={load}>다시 시도</button></>}</div> : content}</Shell>
}
